### ISSUE TITLE
cannot import name 'TabularExplainer' from 'interpret.ext.blackbox'

### ISSUE THREAD

**Issue by HugoAlyona** [microsoft/MCW-Machine-Learning#12]
I tried to run project from official documentation and it does not work due to issue.
https://github.com/microsoft/MLOps/tree/616368d8afbeeed7a9191ffedc56eaf5aed81b43

I saw you closed the same issue 7 days ago, but it does not work

**Comment by shirolkar** [comment]
@HugoAlyona @timahenning 
Hi Hugo - can you clarify which MCW you are having issues with? The link in your comment is for the the `MLOps on Azure` repo. 
If you got this error with the `MCW Machine Learning` https://github.com/microsoft/MCW-Machine-Learning. Can you clarify the notebook and the cell where you saw this error? 
Also, can you check the version of Azure ML SDK in your databricks notebook environment. Here is an example of how you can check the version by running this code in the notebook cell:
```
import azureml.core
print("SDK version:", azureml.core.VERSION)
```
Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no response from field.  Please reopen if needed.

**Comment by Axxeption** [comment]
I have the same issue on Azure Databricks. 

I wanted to use the [local interpretability](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-interpretability-aml#local-interpretability) from Azure ML. 

I successfully installed on my Databricks cluster:
- azureml-interpret
- azureml-sdk[databricks]

Though these were installed I was not able to import the TabularExplainer model with the following command: 
`from interpret.ext.blackbox import TabularExplainer`
This works: but TabularExplainer is not explained when I try to reach to it:
`from interpret.ext.blackbox import *`

My azureML core version is: 1.1.5 
I'm running on a Standard_DS3_v2 machine with the following runtime version: 6.3 (includes Apache Spark 2.4.4, Scala 2.11) 

I hope you can help.

**Comment by shirolkar** [comment]
@Axxeption @timahenning @DawnmarieDesJardins 
Hi Alex - This issue is not directly relevant to the hands on labs in this MCW. The one suggestion I can offer is to add this to the first cell of your notebook and see if that helps.

azureml_sdk_version = '1.1.5'
dbutils.library.installPyPI('azureml-sdk', version=azureml_sdk_version, extras='automl_databricks')
dbutils.library.installPyPI('azureml-interpret', version=azureml_sdk_version)
dbutils.library.installPyPI('azureml-contrib-interpret', version=azureml_sdk_version)
dbutils.library.restartPython()
dbutils.library.list()

In databricks, sometimes the above approach works better than adding it at the cluster level. If it does not work, delete and create a new cluster without adding any libraries, and try running the above suggestion again. If these suggestions do not help. You can log an issue with the following repos: https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/explain-model OR https://github.com/interpretml/interpret-community.

**Comment by Axxeption** [comment]
Thanks for your fast reply!

I installed everything via your way and it worked, but it also works when I install it via the cluster. I did not install the 'azureml-contrib-interpret'. Maybe it should be added explicitly in the docs. 

Thanks!
