### ISSUE TITLE
March 2020 – content update

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Machine-Learning#20]
Suggestion content goes here

**Comment by shirolkar** [comment]
Suggestions for March 2020 updates:

1. Update screenshots to latest in Azure Portal and in  AML Studio.
2. Exercise 1: Clean up steps to register new datasets.
3. Exercise 1: Add model explainability to exercise 1.
4. Exercise 3: There were numerous issues in the past few months with the notebook in exercise 3. The root cause of all such issues is that the version of Azure ML SDK used in training the Auto ML model from the Azure Machine Learning Studio frequently changes and becomes incompatible with the version used in Azure Databricks. Fix this issue by training the Auto ML model in Azure Databricks. In the whiteboard design session, we already discuss the two approaches to Auto ML – using Studio (Exercise 1) and using Azure ML Python SDK (now Exercise 3). We can thus showcase both approaches and address a chronic issue.
5. Exercise 4: Upgrade the deep learning with text model to use a recurrent neural network - LSTM.
6. Exercise 4: Incorporate use in Databricks of MLflow integration with AML.
7. Update the WDS section to reflect all the changes.
